services:
  api:
    image: node:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: npm start

    environment:
      - PORT=5000
      # - DB="postgres://db_user:Hotelhotel8694@wireappsdb-identifier.cd2w6skkyvcq.us-west-2.rds.amazonaws.com:5432/postgres"
      - DB_USER=""
      - DB_PASSWORD=""
      - DB_HOST=""
      - DB_DATABASE=""
